### ISSUE TITLE
Animation in the category sidenavbar

### ISSUE THREAD

**Issue by Rajat012k** [Onestop-Agrotech/Seva-Consumer#85]
Required Behaviour: Clicking on any product category should lead to a smooth transition up to that category.

Current Scenario: No animation(transition) is there.

![image](https://user-images.githubusercontent.com/45823060/94810545-cb7f3a00-0411-11eb-994a-2d7d52a09ff5.png)

**Comment by Chinmay-KB** [comment]
I would like to implement this.
I tried signing up but because I'm not from Bangalore I am unable to see the full ui of the app. Any dummy credentials that you can provide?

**Comment by Nsharma96** [comment]
In address use hagadur as location and select any nearby location.

**Comment by Nsharma96** [comment]
What address did you give ? Make sure its hagadur

**Comment by vikasprashar99** [comment]
> I would like to implement this.
> I tried signing up but because I'm not from Bangalore I am unable to see the full ui of the app. Any dummy credentials that you can provide?



> I would like to implement this.
> I tried signing up but because I'm not from Bangalore I am unable to see the full ui of the app. Any dummy credentials that you can provide?

You have to drag the map to banglore and set it somewhere close to WHITEFIELD area

**Comment by Chinmay-KB** [comment]
I am in the app now.
Could you describe in a bit more detail what kind of  transition you want

**Comment by Rahul-Vijay** [comment]
> I am in the app now.
> Could you describe in a bit more detail what kind of transition you want

Hi thanks for showing your interest. We are looking at smooth transitions between each category when clicked. The animation should slide down or slide up as you tap on any one of the categories.

I suggest you fork the repository first and then send in your PR.
