### ISSUE TITLE
Add Widget Testing for all Screens

### ISSUE THREAD

**Issue by vikasprashar99** [Onestop-Agrotech/Seva-Consumer#87]
The aim of this issue is to add widget tests for all screens.

Also, after writing tests for a screen, make sure to manually test it. In case you don't know how to access that part of the codebase on the app, please contact a member, Feel free to contact us on [Slack](https://app.slack.com/client/T0177HS48UC/C017R7M6AU8) .Thanks!

Widget test needs to be written for following files: -

- [ ]  mainLanding.dart

- [ ] orderScreen.dart

- [ ] details.dart @Rajat012k 

- [ ] newUI.dart

- [ ] location.dart

**Comment by Rajat012k** [comment]
Hi @vikasprashar99 i would like to take details.dart.

**Comment by vikasprashar99** [comment]
> Hi @vikasprashar99 i would like to take details.dart.

assigned thanks!
